_target_: enhancer.data.dataset.EnhancerDataset
root_dir : /scratch/c.sistc3/MS-SNSD/DNS20
name : dns-2020
duration : 5
stride : 2
sampling_rate: 16000
batch_size: 32
min_valid_minutes: 25.0
files:
  train_clean : CleanSpeech_training
  test_clean : CleanSpeech_testing
  train_noisy : NoisySpeech_training
  test_noisy : NoisySpeech_testing
