_target_: enhancer.data.dataset.EnhancerDataset
root_dir : /scratch/c.sistc3/MS-SNSD/DNS30
name : dns-2020
duration : 5.0
sampling_rate: 16000
batch_size: 64
valid_minutes: 30.0
files:
  train_clean : CleanSpeech_training
  test_clean : CleanSpeech_testing
  train_noisy : NoisySpeech_training
  test_noisy : NoisySpeech_testing
