_target_: enhancer.data.dataset.EnhancerDataset
name : vctk
root_dir : /Users/shahules/Myprojects/enhancer/datasets/vctk
duration : 1.0
sampling_rate: 16000
batch_size: 64
num_workers : 0

files:
  train_clean : clean_testset_wav
  test_clean : clean_testset_wav
  train_noisy : noisy_testset_wav
  test_noisy : noisy_testset_wav
