_target_: enhancer.data.dataset.EnhancerDataset
name : vctk
root_dir : /scratch/c.sistc3/DS_10283_2791
duration : 2
stride : 1
sampling_rate: 16000
batch_size: 64
min_valid_minutes : 25
files:
  train_clean : clean_trainset_28spk_wav
  test_clean : clean_testset_wav
  train_noisy : noisy_trainset_28spk_wav
  test_noisy : noisy_testset_wav
